import type { ReactNode } from "react";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function AuthLayout({
  children,
}: {
  children: ReactNode
}) {
  return <>{children}</>;
}
